version: b{build}-{branch}

branches:
  except:
    - dist

environment:
  matrix:
    - platform: x64
      generator: "Visual Studio 15 2017 Win64"
      appveyor_build_worker_image: Visual Studio 2017
    - platform: x86
      generator: "Visual Studio 15 2017"
      appveyor_build_worker_image: Visual Studio 2017
    - platform: x64
      generator: "Visual Studio 14 2015 Win64"
      appveyor_build_worker_image: Visual Studio 2015
    - platform: x86
      generator: "Visual Studio 14 2015"
      appveyor_build_worker_image: Visual Studio 2015
    - platform: x64
      generator: "Visual Studio 12 2013 Win64"
      appveyor_build_worker_image: Visual Studio 2013
    - platform: x86
      generator: "Visual Studio 12 2013"
      appveyor_build_worker_image: Visual Studio 2013

configuration: Debug

clone_folder: c:\wepoll
shallow_clone: true
clone_depth: 1

init:
  - cmd: set

install:
  - ps: Install-Product node 'Current'

before_build:
  - cmd: cmake . -G "%generator%"

build_script:
  - cmd: cmake --build . --config "%configuration%" --target wepoll.dll
  - cmd: cmake --build . --config "%configuration%" --target wepoll-combined.dll

test_script:
  - cmd: cmake --build . --config "%configuration%" --target test-all
